runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: off

handlers:
- url: /js
  static_dir: static/js
  expiration: "1d"
  
- url: /css
  static_dir: static/css
  expiration: "1d"
  
- url: /pic
  static_dir: static/pic
  expiration: "7d"

- url: /tzdata_2011b
  static_dir: static/tzdata_2011b
  expiration: "7d"

- url: /tzdata_2011j
  static_dir: static/tzdata_2011j
  expiration: "7d"

- url: /(.*?).html
  static_files: static/\1.html
  upload: static/(.*?).html
  expiration: "1d"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "7d"

- url: /googlef09a60e23408be60.html
  static_files: static/googlef09a60e23408be60.html
  upload: static/googlef09a60e23408be60.html

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "1d"